model_list:
  - model_name: qwen-3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder:free
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  set_verbose: true
