model_list:
  - model_name: llama3-8b
    litellm_params:
      model: openrouter/meta-llama/llama-3-8b-instruct
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: claude-3-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3-sonnet
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: mistral-7b
    litellm_params:
      model: openrouter/mistralai/mistral-7b-instruct
      api_base: https://openrouter.ai/api/v1
      api_key: os.environ/OPENROUTER_API_KEY

